## Import TensorFlow library

In [1]:
import tensorflow as tf

## TF constant and session

In [4]:
x = tf.constant(3.0)
y = tf.constant(8.1)
with tf.Session() as session:
    print(tf.add(x, y))
    print(session.run(tf.add(x, y)))

Tensor("Add_1:0", shape=(), dtype=float32)
11.1


## TF Graph and Tensorboard

In [5]:
x = tf.constant(3, name="x")
y = tf.constant(8, name="y")
with tf.Session() as session:
    #graph persistence has to be before session execution
    writer = tf.summary.FileWriter(
        '/', session.graph)
    print(session.run(tf.add(x, y)))
#close the graph writer
writer.close()

11


In [6]:
x = tf.constant(3, name='x')
y = tf.constant(8, name='y')
add_op = tf.add(x, y, name='add_op')
with tf.Session() as session:
    writer = tf.summary.FileWriter('test/test002', session.graph)
    print(session.run(add_op))
writer.close()

11


## TF Variable 

In [7]:
x = tf.Variable(2)
y = tf.Variable(3)
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print(session.run(tf.add(x, y)))

5


## Placeholder 

In [10]:
a = tf.placeholder(tf.float32, shape=[3], name="a")
b = tf.constant([5, 5, 5], tf.float32, name="b")
c = a + b # short for tf.add(a, b)
with tf.Session() as session:
    #Error!! because a doesn't have any value
    #print(session.run(c))
    #feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
    print(session.run(c, {a:[1, 2, 3]}))

[ 6.  7.  8.]


## Undeterministic shape can be defined 

In [12]:
a = tf.placeholder(tf.float32, shape=[None, 3], name="a")
b = tf.constant([5, 5, 5], tf.float32, name="b")
c = a + b
with tf.Session() as session:
    print(session.run(c, {a:[[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 5, 7]]}))

[[  6.   7.   8.]
 [  9.  10.  11.]
 [ 12.  13.  14.]
 [  8.  10.  12.]]


## eval() vs session.run() 

## eval() == tf.get_default_session().run(t) 

## Assigment 

In [13]:
W = tf.Variable(1)
W.assign(2)
with tf.Session() as session:
    session.run(W.initializer)
    print(W.eval())

1


In [15]:
W = tf.Variable(1)
#assign_op = W.assign(2)
with tf.Session() as session:
    session.run(W.initializer)
    session.run(W.assign(2))
    print(W.eval())

2


In [17]:
W = tf.Variable(1)
w_double = W.assign(2 * W)
with tf.Session() as sess:
    sess.run(W.initializer)
    # initialize all variables?
    # sess.run(tf.global_variables_initializer())
    for _ in range(10):
        print(sess.run(w_double))

2
4
8
16
32
64
128
256
512
1024


# Tensorboard

In [2]:
import tensorflow as tf
a = tf.constant(2, name='a_constant')
b = tf.constant(3, name='b_constant')
x = tf.add(a, b, name="add_operator")

with tf.Session() as sess:
    writer = tf.summary.FileWriter(
    'test/test003', sess.graph)
    print(sess.run(x))

writer.close()

5


# Interactive Session 

In [5]:
# auto make itself default session
session = tf.InteractiveSession()
a = tf.constant(10.0, name='a_const')
b = tf.constant(20.0, name='b_const')
multi_op = tf.multiply(a, b, name='multiply')
#No need to specifying the context 'session'
writer = tf.summary.FileWriter('test/test001', session.graph)
print(multi_op.eval())
session.close()

200.0


# Advanced Operators

In [13]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name='b')
k = tf.constant([[0, 1], [-1, 3]], dtype=tf.float32, name="k")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="multiply")
with tf.Session() as sess:
    x, y = sess.run([x, y])
    print("x: \n%s\n\n" % x)
    print("y: \n%s\n\n" % y)
    
    z = tf.matmul(x, y, name="matmul")
    print("z: \n%s\n\n" % sess.run(z))
    
    z_zeros = tf.zeros([3, 4], dtype=tf.float32, name="float_zeros")
    print("z_zeros: \n%s\n\n" % sess.run(z_zeros))
    
    z_ones = tf.ones([4, 3], dtype=tf.float32, name="flaot_ones")
    print("z_ones: \n%s\n\n" % sess.run(z_ones))
    
    x_ones_alike = tf.ones_like(x, dtype=tf.float32) # x is the shape to be similar to
    print("x_ones_alike: \n%s\n\n" % sess.run(x_ones_alike))
    
    z_fill = tf.fill([3, 3], value=1.234, name="fill_ns")
    print("z_fill: \n%s\n\n" % sess.run(z_fill))
    
    k_inverse = tf.matrix_inverse(k, name="inverse")
    print("k: \n%s" % k.eval())
    print("k inverse: \n%s\n\n" % k_inverse.eval())

x: 
[[2 3]
 [4 5]]


y: 
[[0 2]
 [4 6]]


z: 
[[12 22]
 [20 38]]


z_zeros: 
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


z_ones: 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


x_ones_alike: 
[[ 1.  1.]
 [ 1.  1.]]


z_fill: 
[[ 1.23399997  1.23399997  1.23399997]
 [ 1.23399997  1.23399997  1.23399997]
 [ 1.23399997  1.23399997  1.23399997]]


k: 
[[ 0.  1.]
 [-1.  3.]]
k inverse: 
[[ 3. -1.]
 [ 1.  0.]]


